New Race Map with Bots
DIT112-V21/group-02 pull request #74
Opened 2021-05-13 15:14 UTC by DrakeAxelrod

This new smce mod includes a new race track with cars that drive
themselves. booster plates to increase the speed of smce during the
race. a minimap to keep track of the posisition of everyone. a clock
that keeps track of the time of the race and each cars finish time.

2021-05-13 20:20 UTC, klarasve commented
Fully functional and works, just need to update one line in arduino file to make mqtt work and show up on website:
`vroom.ino line 79: mqtt.onMessage(+[](String& topic, String& message) `
(by adding + and &)

2021-05-13 20:27 UTC, klarasve requested changes
Fully functional and works, just need to update one line in arduino file to make mqtt work and show up on website:
vroom.ino line 79: mqtt.onMessage(+[](String& topic, String& message)
(by adding + and &)
Also looks really, really good and introduces a lot more functionalities such as minimap and bot cars!

2021-05-17 06:51 UTC, VernitaJ commented on godot-resources/mods/RaceAgainstMod/src/environments/raceagainst/replacements/smoke.gd
> +		$smoke/Smoke.emitting = true
I really like this added feauture

2021-05-17 07:27 UTC, VernitaJ approved these changes
This implementation is working well. The countdown and placement display are great additions for the gaming aspect. Speed boost is great, it's increased the fun in the application massively!
Some small additions to be added to this part of the project including difficulty variations, but that will be separate to this PR. Great job!

2021-05-17 07:59 UTC, klarasve approved these changes
Fully functional and works.

2021-05-17 07:59 UTC, merged

2021-05-17 07:59 UTC, Axel-J-L approved these changes
Great job with this Drake, appreciate working with you on this!